import type { GetServerSideProps, NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import { PrismaClient, Bookmark } from "@prisma/client"
import BookmarkCard from "../components/BookmarkCard"
import Search from "../components/Search"
import Navigation from '../components/Navigation';
import {
  Typography,
  Grid,
  Container,
  Stack,
  Box
} from "@mui/material"

const prisma = new PrismaClient()

export const getServerSideProps: GetServerSideProps = async () => {
  const bookmarks = await prisma.bookmark.findMany()
  return {
    props: {
      bookmarks,
    },
  }
}

type HomeProps = {
  bookmarks: Bookmark[]
}

const Home: NextPage<HomeProps> = ({ bookmarks }) => {
  return (
    <Container>
      <Head>
        <title>Heron&apos;s Haven</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation/>
      <Stack spacing={2}>
        <Search />
        <Box sx={{ flexGrow: 1}}>
          <Grid justifyContent="space-around" alignItems="stretch" container spacing={2}>
            {bookmarks.map((bookmark) => (
              <Grid item xs={2} key={bookmark.id}>
                <BookmarkCard {...bookmark} />
              </Grid>
            ))}
          </Grid>
        </Box>
      </Stack>
    </Container>
  )
}

export default Home
