import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient  } from '@prisma/client'
import Card from '../components/Card'

const prisma = new PrismaClient()

export const getServerSideProps: GetServerSideProps = async (context) => {
  const bookmarks = await prisma.bookmark.findMany()
  console.log(bookmarks);
  return {
    props: {
      bookmarks
    }
  }
}

const Home: NextPage = ({ bookmarks }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Heron's Haven</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Heron's Haven
        </h1>
        
        <div className={styles.grid}>
          {bookmarks.map(bookmark => <Card key={bookmark.id} {...bookmark}/>)}
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
